"""Collection of mappings to harmonise data

@author: jstreeck
"""

STOCKS_OF_MATERIALS = [
    1610,
    1621,
    1622,
    1623,
    1701,
    1702,
    1709,
    2011,
    2013,
    2022,
    2029,
    2030,
    2219,
    2220,
    2310,
    2391,
    2392,
    2393,
    2394,
    2395,
    2396,
    2399,
    2410,
    2420,
    2431,
    2432,
    2511,
    2512,
    2591,
    2592,
    2599,
]

DLS_STOCKS = [
    2011,
    2012,
    2021,
    2023,
    2029,
    2030,
    "2011",
    "2012",
    "2021",
    "2023",
    "2029",
    "2030",
]

HARMONIZE_MATERIALS_DICT = {
    "Wood": "biomass",
    "Paper": "biomass",
    "Chemicals": "fossils",
    "Rubber and plastic": "fossils",
    "non-metallic mineral products": "minerals",
    "basic metals": "metals",
    "fabricated metal products": "metals",
    "construction grade steel": "metals",
    "other": "other",
    "wood and wood products": "biomass",
    "cement": "minerals",
    "paper and cardboard": "biomass",
    "market for textile, woven cotton": "biomass",
    "market for textile, knit cotton": "biomass",
    "market for textile, silk": "biomass",
    "market for textile, nonwoven polypropylene": "fossils",
    "market for textile, nonwoven polyester": "fossils",
    "market for textile, kenaf": "biomass",
    "market for textile, jute": "biomass",
    "market for synthetic rubber": "fossils",
    "sheep production, for wool": "biomass",
    "259:": "metals",
    "concrete": "minerals",
    "iron_steel": "metals",
    "copper": "metals",
    "aluminum": "metals",
    "other_metals": "metals",
    "wood": "biomass",
    "other_biomass": "biomass",
    "bricks": "minerals",
    "mortar": "minerals",
    "gypsum": "minerals",
    "ceramics": "minerals",
    "glass": "minerals",
    "other_minerals": "minerals",
    "plastics": "fossils",
    "bitumen": "fossils",
    "aggregates": "minerals",
}

HARMONIZE_STOCKS_DICT = {
    "mobile_phone": "machinery",
    "stove": "machinery",
    "fridge": "machinery",
    "housing": "res_buildings",
    "mobility": "transport",
    "clothing": "textiles",
    "nonres_buildings": "nonres_buildings",
    "buildings": "nonres_buildings"
}

AGGR_DIM = {
    "communication": "Socialization",
    "clothing": "Shelter",
    "cond_i": "Shelter",
    "education": "Socialization",
    "health": "Health",
    "hh_appliance": "Nutrition",
    "housing": "Shelter",
    "nutrition": "Nutrition",
    "sanitation": "Health",
    "transport": "Mobility",
    "water": "Health",
}

AGGR_DIRECT_INDIRECT_GF = {
            "clothing_i": "clothing",
            "communication_i": "communication",
            "educ_i": "education",
            "education_i": "education",
            "health_i": "health",
            "hh_appliance_i": "hh_appliance",
            "housing_i": "housing",
            "transport_i": "transport",
            "nutrition_i": "nutrition",
            "sanitation_i": "sanitation",
            "water_i": "water",
        }
      
AGGR_PROD = {
    "lamps": "other",
    "motor_vehicles": "transport_machinery",
    "other_transport": "transport_machinery",
    "textiles": "other",
}
